### ISSUE TITLE
valid-package-file-require false positive when filename conflicts with package name

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-mediawiki#17]
If I have
```js
require( 'ext.MyModule' );
```
and `ext.MyModule.js` exists, then the rule marks this as an error, even though this is a perfectly valid name for a package that includes that file.

Rather than doing a complex file check, it might just be better to look for an allowed extension ("js","json", others?)

CC @jakobw @Ladsgroup

**Comment by jakobw** [comment]
Sorry for the late response. I quite like the solution in #21. Only looking for an extension wouldn't have been sufficient since erroring when omitting the extension in a path like `./foo` was exactly the point of this rule. Checking for either the extension or the directory prefix to exist makes sense though!
